name: PostToX

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'  # 毎日3時（UTC）

jobs:
  post:
    runs-on: ubuntu-latest

    env:
      X_API_KEY: ${{ secrets.X_API_KEY }}
      X_API_SECRET: ${{ secrets.X_API_SECRET }}
      X_ACCESS_TOKEN: ${{ secrets.X_ACCESS_TOKEN }}
      X_ACCESS_SECRET: ${{ secrets.X_ACCESS_SECRET }}
      FEED_URL: ${{ secrets.FEED_URL }}
      HASHTAGS: ${{ secrets.HASHTAGS }}
      STATUS_PREFIX: ${{ secrets.STATUS_PREFIX }}
      TEST_MODE: 'false'  # テスト時は true に変更可能

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install feedparser tweepy

      - name: Run post.py
        run: python post.py
